### ISSUE TITLE
Dynamic Commanders Todo

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K#1173]
Commander attributes
- [x] Create dynamic commander unitdef
- [x] Add weapons to commanders, find weapon limit.
- [x] Write commander weapon switching LUS
- [x] Add weapon conversions (probably done with more switching)
- [x] Add battle drones.
- [x] Add personal cloak
- [x] Add radar
- [x] Add jammer
- [x] Add area cloak
- [x] Add personal shield
- [x] Add area shield
- [x] Add nanolathe
- [x] Add range enhancement
- [x] Fix weapon EmitSfx.

Commander ingame interaction and system completion
- [x] Read player commander defs from startscript and set default loadouts.
- [x] Make dynamic comms use skins.
- [x] Make dynamic comms use banners.
- [x] Make start unit setup spawn appropriate dynamic commanders.
- [x] Add trainer commanders to Strider Hub (with a better name)
- [x] Figure out how to make commanders drop appropriate wreckage.
- [ ] Make/set good death clone models for modules. Generic wrecks look bad and debri should not be used for 40% reclaim objects.
- [x] Set chassis morph progression

General tasks
- [x] The UI requires three images for "Accept", "View current modules" and "Cancel".
- [x] Figure out what, if anything, is now broken in missions.
- [x] Make unit power (for experience purposes) match its cost.
- [x] Make unit mass (for transport and impulse) match cost and health.

Interface
- [x] Make Attack AoE widget only take active weapons into account.
- [x] Update Context Menu to take dynamic stats into account.
- [x] Update healthbars to show reload time and manualfire reload times.
- [x] Update selections to show manualfire reload time.
- [x] Make support commanders not make siren warning sounds.
- [x] Fill in commander descriptions and helptext.

Site
- [ ] Set module costs appropriately, fill in balance to match site (or to be improved).
- [ ] Make sure implemented modules (and their costs) match the online system.
- [ ] Remove required modules from the site (Integrated radar network, weapon decorations etc..)
- [x] Make sure site sends decorations and images tables correctly.

Other ideas
- [ ] Replace integrated radar network with an unarmed radar drone module.

**Comment by GoogleFrog** [comment]
Make the unit power (for experience gain purposes) match its cost.

**Comment by sprunk** [comment]
Also mass, for transporting purposes.

**Comment by GoogleFrog** [comment]
Mass:
 * Transportation mass is easy. Every commander is only transportable by Vindicator and transport speed modification is pure lua. It can read a mass override.
 * Impulse and unit pushing is harder. There is no way to change a units mass. Luaed impulse (Gravity Guns, Water, Placeholder) can take a mass modification UnitRulesParam into account.
We can hack something together which holds except for engine impulse. Perhaps make a PR to spring to change unit mass.

Experience:
 * This looks difficult. There is no way to change a unit's power except by using the inbuilt power scale and experience in modrules.
 * gadget:UnitExperience (unitID, unitDefID, unitTeam, newxp, oldxp) exists and commanders could reasonably easily multiply their experience change with it (somewhat harder is recursion is to be avoided).
 * Units hitting a commander will have incorrect XP.
It is probably best to ignore experience and set decent default powers for each of the clonedefs. Perhaps make a PR to spring to change unit power.

**Comment by GoogleFrog** [comment]
Weapon limit is 32. We decided to not have dual wielding of identical weapons.

**Comment by GoogleFrog** [comment]
Clonedefs and death clones:
 * Create one level 0 commander per player per loadout.
 * Create one death clone and debris per player per loadout.
   * Wreckage corresponds to a level 0 comm with no modules.
   * Rezzes to level 0 comm with no modules.
   * Has appropriate name, no level.

**Comment by GoogleFrog** [comment]
We should increase LOS based on weapon range (up to a point).

**Comment by GoogleFrog** [comment]
There are a few major tasks remaining.
 * Fix remaining UI which needs to know about dyncom (start unit setup images, context menu, attack AoE etc..)
 * Make decorations appear on comms. The decorations to use are flags and skins.
 * Remove weapon colour decorations from the site as well as unused modules (integrated radar network and rezz).

**Comment by GoogleFrog** [comment]
Apparently the weapon limit is actually 16.

**Comment by GoogleFrog** [comment]
The commander script has an issue where the incorrect weapon effect is displayed. There is something weird about the sfxtypes.explosiongenerators table and it seems to be size limited. Perhaps SpawnCeg directly with lua is the way to go.

**Comment by GoogleFrog** [comment]
XP is being handled by Sprung who will reimplement XP in lua (for other bonuses apart form the comm XP problem).

**Comment by GoogleFrog** [comment]
The largest remaining task is to make the site work.

**Comment by Licho1** [comment]
What exactly is needed, please post me details somewhere

**Comment by KingRaptor** [comment]
Merging my [dynamicComms](https://github.com/ZeroK-RTS/Zero-K-Infrastructure/tree/dynamicComms) branch into master should probably be sufficient. (will need testing ofc)

**Comment by GoogleFrog** [comment]
A table which looks like this: https://github.com/ZeroK-RTS/Zero-K/blob/master/gamedata/modularcomms/dyncomms_predefined.lua#L2

needs to reach the game. Modules API: https://github.com/ZeroK-RTS/Zero-K/blob/master/modularCommAPI/api_modularcomms.lua

shunts data through, it just needs to arrive in the right format. KingRaptor knows what is going on there. The decorations entries are commented in that file (because static comms don't have decorations) but those keys will get you the decorations.

The site UI does not need significant changes. The largest changes would be to the database entries as I made some cost and module changes. The module defs to translate are here: https://github.com/ZeroK-RTS/Zero-K/blob/master/LuaRules/Configs/dynamic_comm_defs.lua

**Comment by GoogleFrog** [comment]
Disabled shields use up particles. It could be worthwhile to triple the number of clones to only put shields on units which are using them.

**Comment by Orfelius** [comment]
Just saying that the current UI element is just awful. Its counter-intuitive and takes way too much space.

**Comment by GoogleFrog** [comment]
Got a design?

**Comment by sprunk** [comment]
The remaining checkboxes were:
 * move wobble reduction to a drone - irrelevant, wobble reduction removed.
 * site stuff - belongs to the infra repo.
 * wrecks - see #2246
