### ISSUE TITLE
Strike Commander Todo

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K#1204]
- [x] Duplicate models with size scales 1, 1.1, 1.2, 1.25 and 1.3 are required.
- [x] Make a death clone.
- [x] Walk animations.
- [x] Aim animations.
- [x] Death script and animations.
- [x] Everything returned from a script.Something should be an empty piece (shield location, aimFrom etc..).
- [x] Buildpic
- [x] Selection widget large picture

**Comment by GoogleFrog** [comment]
I can do the animations.

**Comment by Anarchid** [comment]
86103d0b3e301e2dac4001e8ccfebba4340e715e adds the following empties for script stuff:
Eye (for aiming)
Shield (no comment)
FingerTipA..C (for fingertip nano emitters)
Palm (for rotating fingers)
