### ISSUE TITLE
Starlight TODO

### ISSUE THREAD

**Issue by Anarchid** [ZeroK-RTS/Zero-K#1455]
- [x] split back for testing
- [x] fix sometimes rotating in wider arc
- [x] make building facing affect initialization direction
- [x] fix requirement for 90-deg snap rotation for docking (by replacing unit visual with piece visual?)
