### ISSUE TITLE
Attrition counter todo

### ISSUE THREAD

**Issue by Anarchid** [ZeroK-RTS/Zero-K#1912]
- [x] remove being able to collapse (prevents ugly green line)
- [ ] add option for displaying rate as an approximate rational fraction (max two digits)
- [ ] add option to not show exact kill/metal counts (saves vertical space)
- [ ] make more resizable vertically (hide some labels or downsize some fonts when appropriate)
- [ ] decouple track-keeping logic from UI, export and expose for other widgets (endgraph) - #2258

**Comment by sprunk** [comment]
I don't think showing as fraction would be useful because it's difficult to compare numbers with changing denominators and with a constant one it's equivalent to showing %.
