### ISSUE TITLE
Planetwars todo

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K#2121]
- [x] Swap a few models. Interception network should use the large radar dish. Planetary grid should use an embiggened version of the tall structure with four tall spires on its corners. Adv wormhole should use the triple wormhole with the rotating things. Bomber factory should be tallk. Dropship factory should have the flat rectangular area.
 - [x] Finish structure placement update. The rectangles are currently created correctly so this is almost done.
 - [x] Implement wormholes that reduce the time taken to evacuate. Basic wormhole evacuates one structure every 10 minutes. Adv evacuates one every 5 minutes. With a missing wormhole you can evacuate once every 20 minutes because I don't want to have such a core mechanic fully disabled by lacking a wormhole. 
 - [x] Check that evacuation works. The defending team should have a global progress bar that is incremented at a rate dependent on the most advanced wormhole generator that they own. When the bar is full they can spend the entire progress on the bar to begin the evacuation of one of their structures. The structure becomes disabled, globally visible and has a teleportation CEG around it (with djinn noise too). After, say, a minute the structure disappears (with a CEG) and is counted as evacuated. The destruction of the defenders most advanced wormhole generator aborts evacuation and their global evacuation progress bar is divided by their own progress rate then multiplied by their new progress rate. See below for the musing that work out these mechanics.
 - [x] Implement structure ownership based on owner tag and then selected by highest planetwars role rank in the game.
 - [x] Implement +% base economy for basic mine and geothermal tap mine (solar array has the drawback of not provided ingame economy for the advantage of being undestroyable).
 - [x] Check that solar array is not disabled by defenders losing a battle (it should only ever be disabled when the planet changes owner).
 - [x] Implement Valk and Vindi build options for dropship factory.
 - [x] Implement bomber build options for the bomber factory.
 - [x] Implement automatically spawning drones for HQ, Garrison and Planetary Grid.
 - [x] Implement some radar (with high emit point) for Interception network and possibly Planetary Grid.
 - [x] Give all structures a bit of LOS. Since we've abandoned the idea of making structures give no advantages we may as well give LOS as it is a small advantage.
 - [x] Think about something to implement for Warp Gate. Possibly make it a Djinn. Maybe just give it a manualfire weapon which EMPS everything nearby in a decent radius.
 - [x] Implement radar jamming (possibly cloaker?) for Warp Jammer.
 - [ ] Think about something to give wormhole inhibitor (stops IP spread) or just give up and leave it with nothing (maybe some drones?).
 - [ ] Give artefact something crazy, Jugglenaut Manualfire?
 - [x] Check that the widgets implementing the ingame objectives display and evacuation count exist and work correctly.
 - [ ] Give wormholes sucking implosions and a bit of a toned down singularity warp explosion effect.

I plan to tackle some of this on Friday and early in the weekend (aka Europe Friday). Other people can do things too and keep the ticket updated. Note that the manual fires should have large cooldowns (minutes) and structures with them should visibly deactivate and reload when the manualfire is not available.

Here are some wormhole evacuation charge thoughts. The simple continuous implementation is as follows:
 * Make the defending team have a wormhole charge progress bar. The bar goes from 0 to 20 and is incremented every second based on your most advanced wormhole. A adv wormhole gives you 4 charge/minute, a basic one gives you 2 charge/minute and with no wormhole you get 1 charge/minute. The bar caps at 20 and is depleted when you activate the evacuation ability on a structure.

The more exciting implementation is as above but with 'local charge' building up on your wormhole. If your most advanced wormhole is destroyed then:
 * The team progress bar is reset to 0.
 * Any evacuations in progress are canceled.

This gives the attackers two targets if they with to prevent the evacuation of a key structure (unless the key structure is the wormhole itself). A less brutal system would be to trade the current charge at the exchange rate set by your new best wormhole. Here is an example:
 * The defenders just have a basic wormhole.
 * Their wormhole is destroyed 8 minutes into the game.
 * They had 16/20 charge which is converted to 8/20 charge (because their wormhole charge generation speed dropped by a factor of 2).

The effect of this mechanic is that having your wormhole destroyed is no worse than never having had that wormhole in the first place. With the reset to 0 mechanic the attackers could delay the evacuation of the first structure by 29 minutes by simply destroying the wormhole in minute 9. However, even with the charge conversion mechanic the attackers can delay evacuation by 30 minutes by destroying the wormhole once evacuation begins at 10 minutes. The wormhole destruction cancels evacuation but it makes sense for the defenders to be weak at this time so it is a good mechanic.

**Comment by GoogleFrog** [comment]
"+% base economy" is not structurally nice and possibly not even a good idea. It is a hard problem to make something intuitive and not broken. How about a bit of standard energy income instead? All this does is saves some metal at the start of the game. The planetwars structures could even have decent pylon radius.

**Comment by Licho1** [comment]
Plain energy income only makes it worthwhile to defend early on.
It's also hard to pick a value which isn't too strong early on, or meaningless very soon.

But let's go for it, let's just pick some sensible flat income energy with decent pylon radius. Sounds like % is hard-er to implement.

**Comment by Anarchid** [comment]
What if it's upgradable, something like geo->moho->singu? Then it's both a shortcut to get more energy and to escalate, and something worth targeting for the attacker.

**Comment by GoogleFrog** [comment]
The death clones need a lot of work:
 - [ ] Hitvolumes are all wrong.
 - [ ] Footprints are all wrong.
 - [ ] Particularly large structures should have no death terrain deformation because the little hole formed just makes the death clone look silly. Alternately, their death crater could be made very large.
 - [ ] Interception Network lacks a death clone.
 - [ ] The metal values are poor. This comes from the poor metal values of structures. Perhaps make structures cost 5x their PW metagame cost. This could make people want to scrap their own structures for the metal, perhaps give planetwars structures a scrap command which turns them into a wreck? This could possibly be an interesting choice for defenders.
 - [ ] Death clones should not be resurrectable.

**Comment by GoogleFrog** [comment]
Simplify wormholes:
 - [ ] If the planet has both an adv and a basic wormhole then only spawn the adv wormhole. Treat the basic wormhole as evacuated in all causes. This implements some wormhole redundancy and could be a decent extra role for the structure. This can all be done gameside with appropriate failures to spawn basic wormholes and server messages at the game end.
 - [ ] Remove the backup wormhole 20 minute evacuation. If the defenders lose their one and only wormhole then they can't evacuate anything.
 - [ ] Make wormhole respond to EMP, disarm and capture. If the wormhole is disabled then pause charge buildup and cancel teleportation. This is pretty harsh so don't get your wormhole EMPed! With the lack of the 20 minute backup evacuation this is no longer a fate worse than death.

**Comment by GoogleFrog** [comment]
The unimplemented mechanics don't require implementation due to other changes.
