### ISSUE TITLE
Lups shield TODO

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K#2490]
- [x] There is no indication of where the back edge of the shield hits the terrain.
![screen00514](https://user-images.githubusercontent.com/1318249/29810197-5d35919c-8ce2-11e7-81ab-a99782729b8d.jpg)
 - [x] Shields don't change colour with charge.
 - [x] Shields are not detected from outside LOS. For large shields we may want to test 8 locations around the edge of the shield for airLOS. For small shields test 4 locations. Test unit visibility first.
 - [x] What do we do for people without lups?

**Comment by GoogleFrog** [comment]
See https://github.com/ZeroK-RTS/Zero-K/pull/2489.

**Comment by Anarchid** [comment]
>  What do we do for people without lups?

People without LUPS don't see nanos, if i guess right? Because both nanolasers and nanoclouds are LUPS.  

This version of a LUPS shield is basically just a sphere; they can render this much.

> There is no indication of where the back edge of the shield hits the terrain.

A frag shader based on the difference between terrain z-buffer and the two ray-sphere intersections could do this very nicely (for each intersect: if depth negative: cull; if depth < margin: glow; otherwise: draw normally). And possibly quite cheaply.

**Comment by GoogleFrog** [comment]
This ticket may be a mistake. I don't think it is worth anyones time to work on this. I made the ticket because I did a little bit of investigation to see what would be required and don't want that work lost.

**Comment by GoogleFrog** [comment]
EvoRTS shields seem to have been improved so it may be worth porting them.

**Comment by GoogleFrog** [comment]
These tasks are complete.
