### ISSUE TITLE
Bomber Fog Chase todo

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K#4771]
Fix or disable prior to stable:
- [ ] Bombers fly too far off target when they are far away.
- [ ] Firing blind at a target that has been invisible for more than a few seconds seems useless.
- [ ] This is even worse for Raven, and probably shouldn't happen after more than a split second, or maybe ever.
- [ ] Most of the water handling behaviour is bad. In particular, Raven gets worse and other bombers waste shots against deep targets.

Nice to have:
- [ ] Radar dots leaving coverage should be handled.
- [ ] Take a look at memory pressure.

**Comment by GoogleFrog** [comment]
Another issue:
-     Have an enemy Glaive patrolling in and out of LOS.
-     Queue Force Fire on the Glaive then Move for a distant Raven.
-     Raven predicts Glaive location with Force Fire, but the Move is lost.
-     The move command doesn't even come back after the Glaive dies.

**Comment by GoogleFrog** [comment]
Ah.
