### ISSUE TITLE
Mod tech deficinices.

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K#5362]
A list of issues with modding and Spring.

**Comment by GoogleFrog** [comment]
Tech-K
- [ ] Units cannot be turned back into nanoframes: https://github.com/beyond-all-reason/spring/issues/1698
- [ ] Little-to-no control over the flight of missiles. No flightTime, acceleration, max speed. https://github.com/beyond-all-reason/spring/issues/1683
- [ ] Wreck dropping is mostly opaque and uncontrollable. There is no reliable way to receive an event about a wreck being dropped due to a particular unit dying, or a way to pre-modify the wreck. https://github.com/beyond-all-reason/spring/issues/1684
- [ ] CEGs etc cannot be scaled up/down to make explosions change size. The mechanics seem to be modifiable, but they would not match the visuals.

**Comment by sprunk** [comment]
> CEGs etc cannot be scaled up/down to make explosions change size.

There's a `d` CEG operator which makes things scale with damage (so you can do `particleCount = "2 d0.01"` or `particleSize = "d0.123"` or whatever). The big caveat is that none of our CEGs use that. The other is that weapons that want scaling can have 0 damage for various reasons.

**Comment by sprunk** [comment]
Related: #4535

**Comment by GoogleFrog** [comment]
> There's a `d` [CEG operator](https://beyond-all-reason.github.io/spring/articles/ceg-operators) which makes things scale with damage (so you can do `particleCount = "2 d0.01"` or `particleSize = "d0.123"` or whatever).

I'm aware of `d`, but I would be surprised if it was flawless. CEG creators would have to think about when it should apply, and with all the accelerations and drags that CEGs use, I would suspect that it would want to be used non-linearly. Which is a pain for CEG.

The ideal would be something akin to passing CEGS a scale when they are created (or having weapons have a scale), and then the engine would scale the images and speeds appropriately to make the CEG appear larger or smaller. There is probably somewhere in the engine where this is simple, where touching the right bit of the recursive structure would make it all work out nicely.

**Comment by codecnotsupported** [comment]
I don't see Pylon energy range or Radar towers range, on this list is that intentional?
Maybe a good it's a idea to remove the advanced radar tower when Tech-K is active and let Radar Tower take over it's functionality if it can be upgraded.
